logsBucket: gs://piqmediaautomation-cb-logs-371441574793

options:
  # opcional (pode deixar assim)
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/ffmpeg/ffmpeg-api:$SHORT_SHA
      - .

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/ffmpeg/ffmpeg-api:$SHORT_SHA
  - us-central1-docker.pkg.dev/$PROJECT_ID/ffmpeg/ffmpeg-api:v1
